FROM maryville/rabbitmq
# somehow I need these...
#RUN rabbitmqctl add_user node node && \
#    rabbitmqctl set_user_tags node management && \
#    rabbitmqctl add_vhost rpc && \
#    rabbitmqctl set_permissions -p /rpc node ".*" ".*" ".*"
