FROM node:alpine

RUN apk add --no-cache openssl && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 && \
    chmod +x /usr/local/bin/dumb-init && \
    apk del openssl

COPY test.js /test.js

ENTRYPOINT ["dumb-init", "--"]

CMD ["node", "/test.js"]
